config/routes.rb
Rails.application.routes.draw do
  root 'rooms#top'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  namespace :users do
    resources :profiles, only: [:edit, :update, :index]
    get 'accounts/index'
   end
  get 'users/index'
  get 'rooms/index'
  get 'rooms/search'
  get 'reservations/confirm'
  get 'reservations/index'
  post '/rooms/:room_id/reservations/confirm' => 'reservations#create'
  resources :rooms
  resources :reservations
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.erb
<header>
  <nav class= "navbar navbar-expand-lg navbar-light bg-black">
    <%= link_to "宿泊予約アプリ", root_path %>
    <% if user_signed_in? %>
      <div class= "d-flex justify-content-end" id= "navbarNav my-2 my-lg-0">
        <ul class= "navbar-nav">
          <li class= "nav-item dropdown">
            <a class= "nav-link dropdown-toggle" id= "navbarDropdown" role= "button" data-toggle= "dropdown" aria-haspopup= "ture" aria-expanded= "false">
              <% if current_user.image? %>
                <%= image_tag current_user.image.url , class: 'profile' %>
              <% else %>
                <%= image_tag '/assets/default-avatar.png',alt: 'プロフィール画像' , class: 'profile' %>
              <% end %>
                <%= current_user.name %>
            </a>
            <div class= "dropdown-menu" aria-labelledby= "navbarDropdown">
              <%= link_to "施設の新規登録", new_room_path, class: "dropdown-item" %>
              <%= link_to "登録済み一覧", rooms_index_path, class: "dropdown-item" %>
              <%= link_to "予約済み一覧", reservations_index_path, class: "dropdown-item" %>
              <%= link_to "アカウント設定", users_profiles_path, class: "dropdown-item" %>
              <%= link_to "ログアウト", destroy_user_session_path, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
      <% else %>
        <div class= "d-flex justify-content-end" id= "navbarNav">
          <ul class= "navbar-nav mr-auto d-flex flex-row">
            <li class= "nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class= "nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
    <% end %>
  </nav>
</header>