config/routes.rb
Rails.application.routes.draw do
  root 'rooms#top'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  namespace :users do
    resources :profiles, only: [:edit, :update, :index]
    get 'accounts/index'
   end
  get 'users/index'
  get 'rooms/index'
  get 'rooms/search'
  get 'reservations/confirm'
  get 'reservations/index'
  post '/rooms/:room_id/reservations/confirm' => 'reservations#create'
  resources :rooms
  resources :reservations
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :reservations, dependent: :destroy
  mount_uploader :home_image, HomeImageUploader
  validates :name, presence: true
  validates :content, presence: true
  validates :address, presence: true
  validates :money, presence: true
  validates :money, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 9_999_999 },
                    format: { with: /\A[0-9]+\z/ }
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @users = current_user
    @rooms = @users.rooms.all
  end

  def new
    @user = current_user
    @room = @user.rooms.new
  end

  def create
    @user = current_user
    @room = @user.rooms.new(params.require(:room).permit(:name, :address, :content, :money, :home_image))
   if @room.save
      flash[:success] = "施設を新規登録しました"
      redirect_to :rooms
   else
      flash.now[:failure] = "登録できませんでした"
      render "new", status: :unprocessable_entity
   end
  end

  def show
    @reservation = Reservation.new
    @room = Room.find(params[:id])
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
     if @room.update(params.require(:room).permit(:name, :address, :content, :money, :home_image))
       flash[:success] = "「#{@room.id}」の情報を更新しました"
       redirect_to :rooms
     else
       flash.now[:failure] = "施設の更新に失敗しました。"
       render "edit", status: :unprocessable_entity
     end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "施設を削除しました"
    redirect_to :rooms
  end

  def search
    @user = current_user.id
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end

  def top
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<h3>施設編集</h3>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<% if flash[:success] %>
  <p class="alert_success"><%= flash[:success] %></p>
<% else flash[:failure] %>
  <p class="alert_failure"><%= flash[:failure] %></p>
 <% end %> 
 
 <%= form_with model: @room do |f| %>
   <table>
     <tr>
       <th><%= f.label :name ,"施設名" %></th>
       <td><%= f.text_field :name %></td>
     </tr>
 
     <tr>
       <th><%= f.label :content ,"施設詳細" %></th>
       <td><%= f.text_area :content %></td>
     </tr>
 
     <tr>
       <th><%= f.label :money ,"料金" %></th>
       <td><%= f.text_field :money %></td>
     </tr>
 
     <tr>
       <th><%= f.label :address ,"住所" %></th>
       <td><%= f.text_field :address %></td>
     </tr>

     <tr>
       <th><%= f.label :home_image ,"画像をアップロード" %></th>
       <td><%= f.file_field :home_image, class: "home_image" %></td>
     </tr>
   </table>
 
   <div>
     <ul>
       <li><%= f.submit "編集を完了する"%></li>
       <li><%= link_to "施設情報に戻る", :rooms %></li>
     </ul>
   </div>
 <% end %>

app/views/rooms/index.html.erb
<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<% if flash[:success] %>
  <p class="alert_success"><%= flash[:success] %></p>
<% else flash[:failure] %>
  <p class="alert_failure"><%= flash[:failure] %></p>
 <% end %> 

 <h3>登録施設一覧</h3>
<table>
  <thead>
    <tr>
      <th>画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>料金</th>
      <th>作成日</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td>
        <% if room.home_image? %>
            <%= image_tag room.home_image.url,class: 'home_image' %>
        <% else %>
            <%= image_tag '/assets/default-home.png',:alt => '施設画像', class: 'home_image' %>
        <% end %>
        </td>
        <td><%= link_to room.name, room %></td>
        <td><%= room.content %></td>
        <td><%= room.money %></td>
        <td><%= room.created_at.strftime("%Y/ %m/ %d") %></td>
        <td><%= link_to "編集", [:edit, room]  %></td>
        <td><%= link_to "削除",room, data: { turbo_method: :delete, turbo_confirm: "施設を削除しますか？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "施設新規登録", :new_room %></p>

app/views/rooms/new.html.erb
<h3>施設新規登録</h3>

<% if flash[:failure] %>
<p class="alert_failure"><%= flash[:failure] %></p>
<% end %> 

 <%= form_with model: @room do |f| %>
   <%= render "rooms/shared/error", model: @room %>
   <table>
     <tr>
       <th><%= f.label :name ,"施設名" %></th>
       <td><%= f.text_field :name, placeholder:"ルーム名を入力" %></td>
     </tr>
 
     <tr>
       <th><%= f.label :content ,"施設詳細" %></th>
       <td><%= f.text_area :content, placeholder:"施設詳細を入力" %></td>
     </tr>
 
     <tr>
       <th><%= f.label :money ,"料金" %></th>
       <td><%= f.text_field :money, placeholder:"一日あたりの料金を入力" %></td>
     </tr>
 
     <tr>
       <th><%= f.label :address ,"住所" %></th>
       <td><%= f.text_field :address, placeholder:"住所を入力" %></td>
     </tr>

     <tr>
       <th><%= f.label :home_image ,"施設画像" %></th>
       <td><%= f.file_field :home_image, placeholder:"画像をアップロード", class: "home_image" %></td>
     </tr>
   </table>
   
   <div>
     <ul>
       <li><%= f.submit "保存する"%></li>
       <li><%= link_to "キャンセル", :rooms %></li>
     </ul>
   </div>
 <% end %>

app/views/rooms/search.html.erb
<%= search_form_for @q, url: rooms_search_path do |f| %>
  <%= f.label :address_cont, "エリア" %>
  <%= f.search_field :address_cont, placeholder: "エリア名を検索" %>
  <%= f.label :name_or_content_cont, "キーワード" %>
  <%= f.search_field :name_or_content_cont, placeholder: "キーワード名を検索" %>
  <%= f.submit "検索" %>
<% end %> 

<p>検索結果：<%= @rooms.count %>件見つかりました</p>
 <table>
 <% @rooms.each do |room| %>
  <tr>
    <th>画像</th>
    <td>
      <% if room.home_image? %>
          <%= image_tag room.home_image.url, class:'home_image' %>
      <% else %>
          <%= image_tag '/assets/default-home.png',:alt => '施設画像', class:'home_image' %>
      <% end %>
    </td>
  </tr>
  <tr>
    <th>施設名</th>
    <td><%= room.name %></td>
  </tr>
  <tr>
    <th>住所</th>
    <td><%= room.address %></td>
  </tr>
  <tr>
    <th>料金</th>
    <td><%= room.money %></td>
  </tr>
  <tr>
    <th>施設詳細</th>
    <td><%= room.content %></td>
  </tr>
  <tr>
    <td><%= link_to "詳細はこちら", room  %></td>
  </tr>
  <% end %>
</table>

app/views/rooms/show.html.erb
<h3>施設詳細</h3>

<%= alert %>
<%= render "rooms/shared/error", model:@reservation %>

<div>
  <ul>
    <li><%= link_to "直前に戻る", :back %></li>
  </ul>
  </div>

<table>
  <tr>
    <th>画像</th>
    <td>
      <% if @room.home_image? %>
          <%= image_tag @room.home_image.url, class:'home_image' %>
      <% else %>
          <%= image_tag '/assets/default-home.png',:alt => '施設画像', class:'home_image' %>
      <% end %>
    </td>
  </tr>
  <tr>
    <th>施設名</th>
    <td><%= @room.name %></td>
  </tr>
  <tr>
    <th>紹介文</th>
    <td><%= @room.content %></td>
  </tr>
  <tr>
    <th>料金</th>
    <td><%= @room.money %></td>
  </tr>
</table>

<%= form_with model: @reservation, method: :get, url:reservations_confirm_path(@room), local: true do |f| %>
    <table>

       <tr>
         <th><%= f.label :start_date ,"チェックイン" %></th>
         <td><%= f.date_field :start_date %></td>
       </tr>
    
       <tr>
         <th><%= f.label :end_date ,"チェックアウト" %></th>
         <td><%= f.date_field :end_date %></td>
       </tr>
       <tr>
         <th><%= f.label :people ,"人数" %></th>
         <td><%= f.text_field :people,  placeholder: "0" %>人</td>
       </tr>

        <%= f.hidden_field:room_id, value:@room.id %>
        <%= f.hidden_field:user_id, value:current_user.id %>

         <td><%= f.submit "予約確認画面へ"  %></td>

    </table> 
<% end %>

app/views/rooms/top.html.erb
<%= search_form_for @q, url: rooms_search_path do |f| %>
    <%= f.label :address_cont, "エリア" %>
    <%= f.search_field :address_cont, placeholder: "エリア名を検索" %>
    <%= f.label :name_or_content_cont, "キーワード" %>
    <%= f.search_field :name_or_content_cont, placeholder: "キーワード名を検索" %>
    <%= f.submit "検索" %>
  <% end %>  

<h3>あなたも素敵な旅に出よう</h3>

<p>おすすめエリア</p>
  <div>
    <span>東京</span>
    <%= link_to image_tag( '/assets/tokyo.jpg', class: "image", alt: "東京"), rooms_search_path(q:{address_cont:"東京"}) %>
  <div>

  <div>
    <span>大阪</span>
    <%= link_to image_tag( '/assets/osaka.jpg', class: "image", alt: "大阪"), rooms_search_path(q:{address_cont:"大阪"}) %>
  <div>

  <div>
    <span>京都</span>
    <%= link_to image_tag( '/assets/kyoto.jpg', class: "image", alt: "京都"), rooms_search_path(q:{address_cont:"京都"}) %>
  <div>

  <div>
    <span>札幌</span>
    <%= link_to image_tag( '/assets/sapporo.jpg', class: "image", alt: "札幌"), rooms_search_path(q:{address_cont:"札幌"}) %>
  <div>